# Generated by Django 3.0.8 on 2020-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='temp_orders',
            name='qty',
            field=models.CharField(max_length=20),
        ),
    ]
