# Generated by Django 3.0.8 on 2020-12-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201211_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='table_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='temp_orders',
            name='table_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='temp_orders',
            name='qty',
            field=models.CharField(max_length=2),
        ),
    ]
