# Generated by Django 3.1.3 on 2020-12-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
