# Generated by Django 3.1.3 on 2020-12-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201217_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
    ]
