# Generated by Django 3.1.3 on 2020-12-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20201219_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='item',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='item',
            field=models.ManyToManyField(null=True, to='orders.Menu'),
        ),
    ]
